[project]
name = "mylib"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11.8"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
